
// запрос на регистрацию
POST http://localhost:3000/users
Content-Type: application/json

{
    "login" : "Василий",
    "password" : "1346",
    "name" : "Alina",
    "surname" : "Zar",
    "age" : 16,
    "address" : "Королёва, 15"
}
###
PUT http://localhost:3000/users
Content-Type: application/json

{
    "login" : "Вася",
    "password" : "1346",
    "name" : "Alina",
    "surname" : "Zar",
    "age" : 16
}

###

GET  http://localhost:3000/products
Content-Type: application/json

###
// запрос на авторизацию
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "login" : "12345678",
    "password" : "1password2"
}

###
//запрос на удаление определённого пользователя
DELETE http://localhost:3000/users 
Content-Type: application/json

{
    "id":20
}

###
// POST запрос на создание новой корзины
POST http://localhost:3000/shoplist
Content-Type: application/json

{
    "user_id" : 1,
    "product_id" : 1,
    "counte" : 28,
    "price" : 2500
}