
// запрос на регистрацию
POST http://localhost:3000/users
Content-Type: application/json

{
    "login" : "Василий",
    "password" : "1346",
    "name" : "Alina",
    "surname" : "Zar",
    "age" : 16,
    "address" : "Королёва, 15"
}
###
PUT http://localhost:3000/users
Content-Type: application/json

{
    "login" : "Вася",
    "password" : "1346",
    "name" : "Alina",
    "surname" : "Zar",
    "age" : 16}

###

GET  http://localhost:3000/products
Content-Type: application/json

###
// запрос на авторизацию
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "login" : "12345678",
    "password" : "1password2"
}

###
//запрос на удаление определённого пользователя
DELETE http://localhost:3000/users 
Content-Type: application/json

{
    "id":20
}

###
// POST запрос на создание новой корзины
POST http://localhost:3000/shoplist
Content-Type: application/json

{
    "user_id" : 7,
    "product_id" : 9,
    "count" : 1,
    "price" : 2500
}

###

GET http://localhost:3000/shoplist/1

###
// POST запрос на создание нового избранного
POST http://localhost:3000/favorites
Content-Type: application/json

{
    "count" : 28,
    "user_id" : 2,
    "product_id" : 7,
    "price" : 2500
}

###

GET http://localhost:3000/favorites/1

###
// POST запрос на создание нового продукта
POST http://localhost:3000/products
Content-Type: application/json

{
    "name" : "Принтер",
    "price" : 2500,
    "rank" : 13,
    "description" : "Чёрный",
    "count" : 29
}

###

GET http://localhost:3000/products/1

###

GET http://localhost:3000/categories